Heading:
  default: "This is a header"
  max: 25
  description:
    en: "Text for the heading in the footer - you can use your site name for example - Max length 25 characters"
    zh_CN: "左侧标题，最多25个字符"
Blurb:
  default: "Ius vitae ornatus at, ei mea sumo quot dicant. Ei tale democritum eos, in mea timeam accumsan forensibus. Ei his aperiam suavitate. Et debitis convenire sea, viris dictas latine."
  max: 180
  description:
    en: "Enter a short blurb about your community - Max length 180 characters"
    zh_CN: "左侧介绍区，最多180个字符。"
Link_sections:
  type: list
  list_type: simple
  default: "官方网站, 请认准官方网站，谨防上当受骗！|官方组织, 社团、学生会、教务处甚至是宿舍游戏联盟！|工具箱, 好用且常用！|商务合作, 谈感情就伤钱了"
  description:
    en: "Add link sections. The ideal number of sections is six. One item per line in this order:<br> Text, title<br><b>Text:</b> what appears on in the footer<br><b>Title:</b> the text that appears when the item is hovered."
    zh_CN: "添加链接分类，最佳为6个。以英文逗号间隔，格式为：<br>名称，介绍<br><b>名称:</b>链接分类的名称<br><b>介绍:</b>鼠标悬停时的介绍文本。"
Links:
  type: list
  list_type: simple
  default: "官方网站, 集美大学, https://www.jmu.edu.cn/, blank, 集美大学|官方网站, 诚毅学院, http://chengyi.jmu.edu.cn/, blank, 集美大学诚毅学院|官方组织, 诚毅招生, http://cyzsb.jmu.edu.cn/, blank|工具箱, 旧版诚毅小家, https://bbs.chengyi.org, blank|商务合作, 合作联系, #,self"
  description:
    en: "Add links to link sections. One item per line in this order:<br>Parent, text, URL, target, title<br>It is a good idea to keep the number of links under each section similar<br><b>Parent:</b> the name of the parent section which this link shows under. Use the `text` value from the list above<br><b>Text:</b> the text that shows for this link<br><b>URL:</b> the path this item links to. You can use relative paths as well.<br><b>Target:</b> Choose whether this item will open in a new tab or in the same tab. Use blank to open the link in a new tab, or use self to open it in the same tab.<br><b>Title:</b> the text that shows when the link is hovered."
    zh_CN: "添加友情链接，以英文逗号间隔，格式为：<br>链接分类名称,友情链接名称,链接地址,打开方式,介绍<br><b>链接分类名称：</b>即上面添加的链接分类名称，可中文<br><b>友情链接名称：</b>即要添加的链接的名称<br><b>链接地址：</b>即URL地址或本地网站相对路径<br><b>打开方式：</b>blank（打开为新标签），self（当前标签打开）<br><b>介绍：</b>鼠标悬停时的介绍文本。"
Small_links:
  type: list
  list_type: simple
  default: "隐私条款, #, self| 新手帮助, #, self| 关于小家, #, self"
  description:
    en: "You can add small links at the bottom of the footer like Terms of Service and Privacy. One item per line in this order:<br>Text, URL, target<br><b>Text:</b> The text that shows for the small link<br><b>URL:</b> The path of the link<br><b>Target:</b> Use blank to open the link in a new tab and use self to open it in the same tab"
    zh_CN: "左侧底部小链接，通常用于添加隐私/服务条款等。以英文逗号间隔，格式为：<br>链接名称,链接地址,打开方式"
Social_links:
  type: list
  list_type: simple
  default: "Facebook, Join us on Facebook, #, blank,fab-facebook|Twitter, show some love on Twitter, #, blank,fab-twitter| Youtube, Check out our latest videos on Youtube, #, blank,fab-youtube"
  description:
    en: "Enter the social links you'd like to add to the footer in this format:<br> provider, title, URL, target<br><b>Provider:</b> is the name of the provider like Facebook or Twitter<br><b>Title:</b> The text that shows when the link is hovered<br><b>URL:</b> The path you'd like the link to have<br><b>Target:</b> Use blank to open the link in a new tab and use self to open it in the same tab<br><b>Icon:</b> use a FontAwesome5 icon name (brand icons need a 'fab-' prefix)."
    zh_CN: "右侧底部图案式链接，以英文逗号间隔，格式为：<br>名称,介绍,链接地址,打开方式,对应的图标名称<br><b>图标名称：</b>请在https://fa5.dashgame.com/#/图标 中查看<br>品牌类图标需添加fab-前缀<br>且在下方svg_icons设置中同步添加。"
Show_footer_on_login_required_page:
  default: true
  description:
    en: "Check this setting if you want the footer to be displayed on the login-required page (only applies if your site is private)"
    zh_CN: "是否在未登录状态下仍然显示此页脚？（仅适用于私有站点）"
svg_icons:
  default: "fab-facebook|fab-twitter|fab-youtube"
  type: "list"
  list_type: "compact"
  description:
    en: "List of FontAwesome 5 icons used in the social links setting above. "
    zh_CN: "品牌类图标需添加fab-前缀，例如fab-qq"
